version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: maple-leaf-db
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - maple-leaf-be-db
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  springboot:
    build: .
    container_name: maple-leaf-server
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SSL_PWD: ${SSL_PWD}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: ${REDIS_HOST}
      JWT_PASSWORD: ${JWT_PASSWORD}
    ports:
      - "45000:8080"
    restart: always
    networks:
      - maple-leaf-be-db

  redis:
    image: redis:7.0-alpine
    container_name: maple-leaf-redis
    networks:
      - maple-leaf-be-db
    restart: always

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    networks:
      - maple-leaf-be-db

networks:
  maple-leaf-be-db:
    external: true
