version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: maple-leaf-db
    platform: linux/x86_64
    env_file:
     - "./db/.env"
    networks:
      - maple-leaf-be-db
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
    restart: always

  springboot:
    build: .
    container_name: maple-leaf-server
    depends_on:
      - mysql
    env_file:
      - "./backend/.env"
    ports:
      - "8080:8080"
    restart: always
    networks:
      - maple-leaf-be-db

  redis:
    image: redis:7.0-alpine
    container_name: maple-leaf-redis
    networks:
      - maple-leaf-be-db

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - maple-leaf-be-db

networks:
  maple-leaf-be-db:
    name: maple-leaf-db-db
