name: Auto Comment

on:
  pull_request:
    types:
      - opened

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpenedReactions: '+1'
          issuesOpenedComment: |
            LGTM 👍(･ω･)👍
          pullRequestOpenedReactions: '+1'
          pullRequestOpened: |
            LGTM 👍(･ω･)👍
